version: '3.8'

services:
  prometheus-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - PROMETHEUS_USERNAME=${PROMETHEUS_USERNAME:-}
      - PROMETHEUS_PASSWORD=${PROMETHEUS_PASSWORD:-}
      - PROMETHEUS_TOKEN=${PROMETHEUS_TOKEN:-}
    restart: unless-stopped
    stdin_open: true
    tty: true
