name: Build and Push Kafka Exporter Docker Image

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Build"
        required: true
        default: "World"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 登录到 GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 命名小写
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GHTK}

      # 构建 Docker 镜像
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${REPO}:${{ github.sha }} -f Dockerfile .

      # 推送 Docker 镜像
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${REPO}:${{ github.sha }}

      # 可选：推送带有最新标签的镜像
      - name: Push Docker Image with latest tag
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ghcr.io/${REPO}:${{ github.sha }} ghcr.io/${REPO}:latest
          docker push ghcr.io/${REPO}:latest
